# Generated by Django 6.0.3 on 2026-04-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название термина')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('source', models.CharField(max_length=255, verbose_name='Источник (ГОСТ/закон)')),
                ('source_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на источник')),
            ],
            options={
                'verbose_name': 'Термин',
                'verbose_name_plural': 'Термины',
                'ordering': ['name'],
            },
        ),
    ]
