# Generated by Django 6.0.3 on 2026-04-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='source',
            field=models.CharField(max_length=255, verbose_name='Источник'),
        ),
    ]
