# Generated by Django 6.0.3 on 2026-04-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_term_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='source',
        ),
        migrations.RemoveField(
            model_name='term',
            name='source_link',
        ),
        migrations.AddField(
            model_name='term',
            name='gost_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в соответствии с ГОСТ'),
        ),
    ]
