# Generated by Django 6.0.3 on 2026-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_term_source_remove_term_source_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='gost_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
